### ISSUE TITLE
Closing Tab With Keyboard Shortcut Causes JS Exception

### ISSUE THREAD

**Issue by jeff0282** [minbrowser/min#2069]
- **Min Version: v1.25.1**
- **Electron Version: v102.0.5005.167**
- **Operating system: Arch Linux**

## Expected Behavior
Upon pressing the keybinding for closing a tab, the tab should close in the same manner as when closed via the button on the tab. 

## Actual Behavior
Min immediately crashes due to a JavaScript error occurring in the main process.

The Contents of the Error Message:
```
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'loadedInitialURL')
    at setView(/usr/lin/min/main.build.js:1720:26)
    at lpcMainlmpl.<anonymous> (/usr/lib/min/main.build.js:1776:3)
    at lpcMainlmpl.emit (node:events:526:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11014)
    at EventEmitter.emit (node:events:526:28)
```

(the close button on the tabs themselves work fine, it just seems to be when using the keyboard shortcut).

## To Reproduce
1. Start Min And Open Multiple Tabs
2. Attempt To Close A Tab Using The Keyboard Shortcut (In My Case: CTRL+Q)

Min Immediately Crashes and Exits Upon Closing The Error Popup

**Comment by jeff0282** [comment]
Apologies, this seems to have been user error.


# What I Did Wrong
I believe this was caused by me thinking that leaving a Keyboard Shortcut blank would disable it. However, it seems that it resets to the default.

I had remapped closing of tabs to CTRL+Q and left the Keybinding for exiting Min blank, thinking it would disable it. In reality what this did was cause 2 actions to be mapped to one keybind, as CTRL+Q is the default keybind to close Min.

My solution was simply remapping the keybind to close Min to SHIFT+CTRL+Q. I have not encountered the issue since.

---

I'll close this given it's not a bug, though I do believe some clarification on Keybinds (that they'll reset to default if you leave then blank, rather than be disabled) would be most helpful for new users.

**Comment by PalmerAL** [comment]
This is still kind of our fault (closing a tab and quitting the browser at the same time shouldn't crash), so I'm going to reopen. This is an interesting edge case, thanks for finding it.
