### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by edi2004** [minbrowser/min#2335]
- **Min Version:** v1.29.0
- **Operating system:** macOS 10.15.7 Catalina

## Expected Behavior
Navigating to other URLs like normal.

## Actual Behavior
An alert window show up with title:
"A JavaScript error occurred in the main process"
Body error message: 
Uncaught Exception:
TypeError: Cannot read properties of null (reading 'id')
    at /Applications/Min.app/Contents/Resources/app/main.build.js:2132:81
    at Array.find (<anonymous>)
    at Function.<anonymous> (/Applications/Min.app/Contents/Resources/app/main.build.js:2132:51)

## To Reproduce
Changing URLs in address/title bar and then press ENTER to navigate to the new URLs.
![Screen Shot 2023-10-30 at 14 41 34](https://github.com/minbrowser/min/assets/195604/667ffa0f-9d36-420e-8ab8-6922d124ccd1)

**Comment by PalmerAL** [comment]
Did this work in the past, or did you just install Min for the first time? Does it still happen after restarting the browser?

**Comment by edi2004** [comment]
Yes, it is worked perfectly in the past.
I'm reinstalling Min by copying the new Min.app to the Application folder.
