### ISSUE TITLE
Blank Screen on Debian 12

### ISSUE THREAD

**Issue by gaelzarco** [minbrowser/min#2347]
I am new to Linux and am experiencing a bug where the top of the window turns blank. This can be the tab bar in the browser or the top of the window on the settings page. This happens within seconds of opening the application. I am running Debian 12 and Min v1.29.0-amd64.

**Comment by wout145** [comment]
Same issue here. I can add that I get the following error message: 
`
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at sendIPCToWindow (/opt/Min/resources/app/main.build.js:943:24)
    at BrowserWindow.<anonymous> (/opt/Min/resources/app/main.build.js:1078:5)
    at BrowserWindow.emit (node:events:525:35)
`

**Comment by PalmerAL** [comment]
I think this is fixed in 1.30, which I just published today - can you try that and report back?

(If so, this is a duplicate of #2321)
