### ISSUE TITLE
A JavaScript error occurred in the main process, on opening Min, Mac x86_64

### ISSUE THREAD

**Issue by mingmamma** [minbrowser/min#2488]
Really love the low memory footprint of this browser (used on another machine before)! Just now downloaded the Mac install, and it was my bad doing "some stuff" (i.e. drag the `Min.app` folder from `/Users/my_name/Downloads` to `Users/my_name/Applications/` to open the app, and then force quit, and then `rm -rf Min.app` given the app was a bit irresponsive, and then re-downloaded `Min.app` to see the following error message, and probably a bunch of other silly actions from a stupid user in-between that I cannot list here accurately... 😞 

I am posting to see if this error message would look familiar to the project maintainers as in you would see some quick actions to for attempting to troubleshoot such issue, for example `rm some_folder_you_know`...
I myself have tried `rm -rf /private/var/folders/2k/yqztx7j11_70cvfdxc0p1bl80000gn/T/AppTranslocation/C35C96FF-761B-48D8-8F26-DAE184599B5E/d/Min.app/`, just naively as something reported in the error message, to no avail (there seems to be permission restriction from MacOs on that folder, which I learned from ChatGPT that on a high-level is something user shouldn't be touching)...

If you cannot see anything obvious, don't trouble to make much effort on this issue

```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected non-whitespace character after JSON at position 125 (line 1 column 126)
at JSON.parse (<anonymous>)
at Object.initialize (/private/var/folders/2k/yqztx7j11_70cvfdxc0p1bl80000gn/T/AppTranslocation/C35C96FF-761B-48D8-8F26-DAE184599B5E/d/Min.app/Contents/Resources/app/main.build.js:971:28)
at Object.<anonymous> (/private/var/folders/2k/yqztx7j11_70cvfdxc0p1bl80000gn/T/AppTranslocation/C35C96FF-761B-48D8-8F26-DAE184599B5E/d/Min.app/Contents/Resources/app/main.build.js:1054:10)
at Module._compile (node:internal/modules/cjs/loader:1256:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
at Module.load (node:internal/modules/cjs/loader:1098:32)
at Module._load (node:internal/modules/cjs/loader:945:12)
at c._load (node:electron/js2c/node_init:2:13672)
at node:electron/js2c/browser_init:2:121151
at node:electron/js2c/browser_init:2:121360
```

**Comment by PalmerAL** [comment]
This looks like the same issue as #2483, which I coincidentally just fixed a few days ago. In the meantime, you can work around it by deleting `~/Library/Application Support/Min/settings.json`.

**Comment by mingmamma** [comment]
And of course that works like a charm on my end :)
