### ISSUE TITLE
Add Mouse3 scrolling

### ISSUE THREAD

**Issue by SpecialBomb** [minbrowser/min#415]
In chrome and firefox, a common feature to scroll in both directions is to press the middle mouse button while moving your cursor in the direction you want to scroll.

**Comment by PalmerAL** [comment]
Interesting, didn't know about that. I would think this would be built into Electron - does it not work in the main Min UI as well, or just in the webviews?

**Comment by SpecialBomb** [comment]
Nope. Maybe there is some sort option to be enabled?

**Comment by BlueManCZ** [comment]
_Mouse3 scrolling is feature of Windows._

**Comment by SpecialBomb** [comment]
Mouse3 scrolling works in Linux and Windows, not sure about mac. I use
Debian and use mouse3 scrolling in firefox all of the time. Dunno what you
are talking about.

**Comment by BlueManCZ** [comment]
I use Debian 10 with KDE Plasma 5.8.7 and mouse3 scrolling in Firefox doesn't work. Maybe there is any difference between environments. I don't know.

Btw, are we talking about this?
![firefoxautoscroll](https://user-images.githubusercontent.com/17854950/30828844-4191b502-a23f-11e7-8ac8-4a6368c70d24.jpg)

**Comment by code-hunger** [comment]
It doesn't work for me in Chromium on Arch, either.

**Comment by SpecialBomb** [comment]
@BlueManCZ Firefox is weird, you have to enable "use autoscrolling" in the advanced preferences.

Yes, we are talking about that.

**Comment by code-hunger** [comment]
Chromium on ArchLinux: what SpecialBomb talks about *does* work for me; What BlueManCZ talks about does *not*.
--- About the last SpecialBomb's comment - it works for me but I don't get this scroll circle.

Can't test in min as I get startup errors now.

**Comment by PalmerAL** [comment]
> Can't test in min as I get startup errors now.

@code-hunger What error are you getting?

**Comment by code-hunger** [comment]
Can't copy the text, pasting as screenshot:
![2017-09-26_12 45 06](https://user-images.githubusercontent.com/11772321/30853855-97bb7f0c-a2b8-11e7-9ded-677588b5cb0a.png)

I get this on the latest commit 280bde25a227cf4fe38b3767e4fe3244c8a01b55

**Comment by code-hunger** [comment]
I tried `electron .` a after `git checkout HEAD~10` few times and still get the error. That's really weird.

I'm on 280bde25a227cf4fe38b3767e4fe3244c8a01b55 now (from Aug 17, '17) and I have no idea why this happens. Perhaps some cached scripts that need cleaning or something broken with my local git repo?

**Comment by PalmerAL** [comment]
@code-hunger Now that Min supports multiple languages, need to run ```npm run buildTranslations``` before running ```grunt``` so that the language files can be included in the bundled JS.

**Comment by SpecialBomb** [comment]
@PalmerAL Really? I actually had to run grunt first, then build the translations or I would get an error trying to run the buildTranslations script. If I didn't run grunt first, I would get @code-hunger 's error.

Also to note, I have been using the latest version of electron to develop min. What is interesting is that the bug in linux where the page won't render won't happen at all, which is good. I also get segfaults, but I think that's because I left the debug headers in, but what do I know.

**Comment by code-hunger** [comment]
Thanks, PalmerAL;
For me, running `npm run buildTranslations` after `grunt` gave me the error again, so I did it as PalmerAl says with `grunt` after npm and got it working.

**Comment by SpecialBomb** [comment]
Hmm, strange. This is the output I get if I don't run grunt first:

```
npm run buildTranslations

> min@1.6.2 buildTranslations /home/specialbomb/min
> node ./scripts/buildLocalization.js

fs.js:653
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/specialbomb/min/dist/localization.build.js'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.writeFileSync (fs.js:1300:33)
    at Object.<anonymous> (/home/specialbomb/min/scripts/buildLocalization.js:32:4)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! min@1.6.2 buildTranslations: `node ./scripts/buildLocalization.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the min@1.6.2 buildTranslations script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.3.0 → 5.4.2    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:
npm ERR!     /home/specialbomb/.npm/_logs/2017-09-27T18_56_03_537Z-debug.log
```

However, if I run grunt first, the dist directory suddenly appears, therefore not giving me any errors because the file exists. I think this should be addressed. I am using Debian 9 stretch, so it may be a linux thing, as you are all using macs from the looks of it.

**Comment by code-hunger** [comment]
I'm using ArchLinux but for me `dist/` has been already created by previous builds - that explains why I didn't get the error SpecialBomb's getting.

**Comment by SpecialBomb** [comment]
I see, I tested in a fresh clone to get that error. I suggest doing the same and see what happens.

**Comment by code-hunger** [comment]
Bang! Yes. Removed `dist/` and got the error. I'll try to see where it comes from...

**Comment by SpecialBomb** [comment]
Well, it comes from grunt. Grunt creates the dir on a fresh clone.

**Comment by PalmerAL** [comment]
Running the translations script on a fresh clone is fixed in 26518c5c212d567280d5ba80ab3ac3473064816b.

@code-hunger You're probably right, but I'm planning on replacing grunt anyway (#307), so I'm not sure it's worth converting it.
