### ISSUE TITLE
Error Msg on Malicious page detected

### ISSUE THREAD

**Issue by jgclark** [minbrowser/min#80]
I had the following message pop up when I got a red "Malicous page detected" page:

```
A JavaScript error has occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'delete' of undefined
    at ObjectsRegistry.remove (/Applications/Min.app/Contents/Resources/atom.asar/browser/objects-registry.js:53:31)
    at EventEmitter.<anonymous> (/Applications/Min.app/Contents/Resources/atom.asar/browser/rpc-server.js:345:26)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/Applications/Min.app/Contents/Resources/atom.asar/browser/api/web-contents.js:134:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

v1.1.2

**Comment by PalmerAL** [comment]
The phishing detection feature has been removed, so this shouldn't be an issue any more.
